In [2]:
# Jupyter Notebook

# Importing required libraries

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

In [3]:
# Reading the dataset
df = pd.read_csv("Data_to_ModelBuilding.csv")

# Display the first few rows of the dataset
df.head()

,YearsFromRegistration,powerPS,kilometer,abtest_test,vehicleType_cabrio,vehicleType_coupe,vehicleType_limousine,vehicleType_others,vehicleType_small car,vehicleType_station wagon,...,fuelType_lpg,fuelType_other,fuelType_petrol,gearbox_manual,notRepairedDamage_yes,brand_encoded,monthOfRegistration_Q2,monthOfRegistration_Q3,monthOfRegistration_Q4,price
0,20,150,150000,1,0,0,1,0,0,0,...,0,0,0,1,0,2,0,0,0,4450
1,18,163,150000,0,0,0,0,0,0,0,...,0,0,0,1,0,39,1,0,0,13299
2,20,101,150000,1,0,0,0,0,0,0,...,0,0,0,1,0,38,0,0,1,3200
3,17,86,60000,0,0,0,0,0,1,0,...,0,0,1,1,0,30,0,0,1,4500
4,15,185,150000,1,0,0,0,0,0,0,...,0,0,0,0,0,39,0,0,1,18750

# Train test split

In [4]:
from sklearn.model_selection import train_test_split

# Extracting target variable
y = df.pop('price')
X = df

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the first few rows of the training set
X_train.head()

,YearsFromRegistration,powerPS,kilometer,abtest_test,vehicleType_cabrio,vehicleType_coupe,vehicleType_limousine,vehicleType_others,vehicleType_small car,vehicleType_station wagon,...,fuelType_hybrid,fuelType_lpg,fuelType_other,fuelType_petrol,gearbox_manual,notRepairedDamage_yes,brand_encoded,monthOfRegistration_Q2,monthOfRegistration_Q3,monthOfRegistration_Q4
3834,19,69,90000,1,0,0,0,0,1,0,...,0,0,0,1,1,1,10,0,0,0
17567,17,170,150000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,38,1,0,0
35930,26,125,150000,1,0,1,0,0,0,0,...,0,0,0,1,1,0,1,0,0,0
4528,12,170,90000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,20,0,0,1
17204,21,177,50000,0,0,0,1,0,0,0,...,0,0,0,1,0,0,20,0,1,0

# Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Select columns to scale
columns_to_scale = ['YearsFromRegistration', 'powerPS', 'kilometer', 'brand_encoded']

# Fit the scaler on the training data and transform it
X_train_scaled = scaler.fit_transform(X_train[columns_to_scale])

# Use the same scaler to transform the test data
X_test_scaled = scaler.transform(X_test[columns_to_scale])

# Replace the original columns with the scaled ones in both training and test sets
X_train[columns_to_scale] = X_train_scaled
X_test[columns_to_scale] = X_test_scaled

In [ ]:
# Display the first few rows of the scaled training set
X_train.head()

# Regression

In [5]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso, BayesianRidge, HuberRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
# Initialize and Train Models
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'Bayesian Ridge': BayesianRidge(),
    'Huber Regressor': HuberRegressor(),
    'SVR': SVR(),
    'KNN': KNeighborsRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest': RandomForestRegressor(),
    'Gradient Boosting': GradientBoostingRegressor(),
    'XGBoost': XGBRegressor(),
}

# Results dictionary
results = {'Model': [], 'MSE': [], 'R-squared': []}

# Loop through each model
for model_name, model in models.items():
    # Train the model on the training set
    model.fit(X_train, y_train)
    
    # Make Predictions
    y_pred = model.predict(X_test)
    
    # Evaluate Model Performance
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Store results in the dictionary
    results['Model'].append(model_name)
    results['MSE'].append(mse)
    results['R-squared'].append(r2)

# Display Results
results_df = pd.DataFrame(results)
print(results_df)